spring.application.name=javashop


spring.datasource.url=jdbc:postgresql://localhost:5432/javashop
spring.datasource.username=javashop
spring.datasource.password=javashop

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true